### ISSUE TITLE
command `moleculer` won't execute

### ISSUE THREAD

**Issue by dydx** [ice-services/moleculer-cli#1]
**My environment**: 

OS: Darwin failbowl.turner.com 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

Node: v7.9.0
NPM: 4.2.0

Issue:

After running `npm install -g moleculer-cli`, the `moleculer` command will not execute properly. This appears to be related to some newline encoding within `bin/moleculer.js`.

```
❯ moleculer
env: node\r: No such file or directory
```

**Comment by icebob** [comment]
Thank you the PR. I'm on Windows.

**Comment by dydx** [comment]
Awesomesauce! Thanks for the cool software.

**Comment by dydx** [comment]
Hmm. It appears to still be acting up:

```
❯ npm install -g moleculer-cli
/Users/josh/.nvm/versions/node/v7.9.0/bin/moleculer -> /Users/josh/.nvm/versions/node/v7.9.0/lib/node_modules/moleculer-cli/bin/moleculer.js
/Users/josh/.nvm/versions/node/v7.9.0/lib
└── moleculer-cli@0.3.1


❯ moleculer
env: node\r: No such file or directory
```

**Comment by icebob** [comment]
I think, CRLF will be the problem. I'm fixing...

**Comment by icebob** [comment]
Please try the 0.3.2.

**Comment by dydx** [comment]
👍 that appears to have fixed it!

**Comment by icebob** [comment]
Great! Thanks for your help!
